services:
  - type: web
    name: lost-ark-backend
    runtime: node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js

  - type: static
    name: lost-ark-frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build